package com.mehran.KTBooks.models.enums;

public enum Genre {
    FICTION("Fiction"),
    NON_FICTION("Non-Fiction"),
    FANTASY("Fantasy"),
    SCIENCE_FICTION("Science Fiction"),
    MYSTERY("Mystery"),
    THRILLER("Thriller"),
    HORROR("Horror"),
    HISTORICAL_FICTION("Historical Fiction"),
    ROMANCE("Romance"),
    YOUNG_ADULT("Young Adult"),
    CHILDREN("Children"),
    ADVENTURE("Adventure"),
    DYSTOPIAN("Dystopian"),
    MEMOIR("Memoir"),
    BIOGRAPHY("Biography"),
    SELF_HELP("Self-Help"),
    GRAPHIC_NOVEL("Graphic Novel"),
    POETRY("Poetry"),
    CRIME("Crime"),
    LGBTQ_PLUS("LGBTQ+"),
    CLASSIC("Classic"),
    CONTEMPORARY("Contemporary"),
    PARANORMAL("Paranormal"),
    SCIENCE("Science"),
    PSYCHOLOGY("Psychology"),
    TRAVEL("Travel"),
    HUMOR("Humor"),
    RELIGION("Religion"),
    SPIRITUALITY("Spirituality"),
    TRUE_CRIME("True Crime"),
    COOKBOOK("Cookbook"),
    POLITICAL("Political"),
    PHILOSOPHY("Philosophy"),
    ART("Art"),
    MUSIC("Music"),
    SPORTS("Sports"),
    BUSINESS("Business"),
    HISTORY("History"),
    DRAMA("Drama"),
    WAR("War"),
    MYTHOLOGY("Mythology"),
    FAIRY_TALE("Fairy Tale"),
    ANTHOLOGY("Anthology"),
    ESSAY("Essay"),
    SHORT_STORY("Short Story"),
    WESTERN("Western"),
    URBAN_FANTASY("Urban Fantasy"),
    EPIC_FANTASY("Epic Fantasy"),
    MAGICAL_REALISM("Magical Realism"),
    SPACE_OPERA("Space Opera"),
    CYBERPUNK("Cyberpunk"),
    STEAMPUNK("Steampunk"),
    POST_APOCALYPTIC("Post-Apocalyptic"),
    TIME_TRAVEL("Time Travel"),
    DARK_FANTASY("Dark Fantasy"),
    CHICK_LIT("Chick Lit"),
    NEW_ADULT("New Adult"),
    LEGAL_THRILLER("Legal Thriller"),
    MEDICAL_THRILLER("Medical Thriller"),
    POLITICAL_THRILLER("Political Thriller"),
    DETECTIVE("Detective"),
    COZY_MYSTERY("Cozy Mystery"),
    EROTICA("Erotica"),
    FOLKLORE("Folklore"),
    INDUSTRIAL("Industrial"),
    COMING_OF_AGE("Coming of Age"),
    BILDUNGSROMAN("Bildungsroman"),
    ALTERNATE_HISTORY("Alternate History"),
    INSPIRATIONAL("Inspirational"),
    EDUCATIONAL("Educational"),
    ACADEMIC("Academic"),
    NATURE("Nature"),
    ENVIRONMENT("Environment"),
    HEALTH("Health"),
    WELLNESS("Wellness"),
    CRAFTS("Crafts"),
    HOBBIES("Hobbies"),
    DIY("DIY");

    private final String name;

    Genre(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }
}
